ERROR_RESPONSES = [
    "Hmm, something went wrong there. Want to try again?",
    "Oops! That didn't go as planned. Let's give it another shot.",
    "Uh-oh, looks like I ran into a hiccup. Can you check that for me?",
    "Sorry, I couldn't handle that request. Maybe try rephrasing it?",
    "Yikes, I hit a snag. Let's see if we can fix it together.",
    "Oh no, that didn't work. How about trying again?",
    "Hmm, I couldn't get that done. Maybe double-check the details?",
    "Looks like I need a little help with this one. Care to try again?",
    "Something didn't click on my end. Let's take another crack at it.",
    "Whoops! I missed the mark. Mind giving it another go?",
    "Sorry about that! I'm here if you want to try once more.",
    "That didn't work out. Let's reset and try again.",
    "Oops, I fumbled that one. Can you give me another chance?",
    "Hmm, I hit a roadblock. Let's try something different.",
    "Looks like something went sideways. Let's figure it out together.",
    "Sorry, I stumbled there. Want to have another go?",
    "Oh no, I couldn't complete that. Let me know how I can help.",
    "Oops, I got stuck. Want to check and try again?",
    "Hmm, that's on me. How about we try a different approach?",
    "Something didn't work out. Let's retry and get it right!"
]